// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// penreg_Rcpp
arma::vec penreg_Rcpp(arma::vec Y, arma::mat X, double lambda, arma::vec beta0, List control);
RcppExport SEXP _rrpack_penreg_Rcpp(SEXP YSEXP, SEXP XSEXP, SEXP lambdaSEXP, SEXP beta0SEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(penreg_Rcpp(Y, X, lambda, beta0, control));
    return rcpp_result_gen;
END_RCPP
}
// penreg_Rcpp_XY
arma::vec penreg_Rcpp_XY(arma::vec XY, arma::mat XX, double lambda, arma::vec beta0, List control);
RcppExport SEXP _rrpack_penreg_Rcpp_XY(SEXP XYSEXP, SEXP XXSEXP, SEXP lambdaSEXP, SEXP beta0SEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type XY(XYSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type XX(XXSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta0(beta0SEXP);
    Rcpp::traits::input_parameter< List >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(penreg_Rcpp_XY(XY, XX, lambda, beta0, control));
    return rcpp_result_gen;
END_RCPP
}
// procrustes_RCpp
Rcpp::List procrustes_RCpp(arma::mat XY, arma::mat XX, arma::mat D, double rho2, arma::mat U, Rcpp::List control);
RcppExport SEXP _rrpack_procrustes_RCpp(SEXP XYSEXP, SEXP XXSEXP, SEXP DSEXP, SEXP rho2SEXP, SEXP USEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type XY(XYSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type XX(XXSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type D(DSEXP);
    Rcpp::traits::input_parameter< double >::type rho2(rho2SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type U(USEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(procrustes_RCpp(XY, XX, D, rho2, U, control));
    return rcpp_result_gen;
END_RCPP
}
// MGlasso_Rcpp
Rcpp::List MGlasso_Rcpp(arma::mat Y, arma::mat X, arma::vec lam, arma::mat B0, double conv, int maxiter);
RcppExport SEXP _rrpack_MGlasso_Rcpp(SEXP YSEXP, SEXP XSEXP, SEXP lamSEXP, SEXP B0SEXP, SEXP convSEXP, SEXP maxiterSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type lam(lamSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B0(B0SEXP);
    Rcpp::traits::input_parameter< double >::type conv(convSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    rcpp_result_gen = Rcpp::wrap(MGlasso_Rcpp(Y, X, lam, B0, conv, maxiter));
    return rcpp_result_gen;
END_RCPP
}
// srrr_Rcpp
Rcpp::List srrr_Rcpp(arma::mat Y, arma::mat X, String method, arma::mat A0, arma::mat V0, int nrank, double lambda, double conv, int maxiter, double inner_conv, int inner_iter, arma::vec WA);
RcppExport SEXP _rrpack_srrr_Rcpp(SEXP YSEXP, SEXP XSEXP, SEXP methodSEXP, SEXP A0SEXP, SEXP V0SEXP, SEXP nrankSEXP, SEXP lambdaSEXP, SEXP convSEXP, SEXP maxiterSEXP, SEXP inner_convSEXP, SEXP inner_iterSEXP, SEXP WASEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type A0(A0SEXP);
    Rcpp::traits::input_parameter< arma::mat >::type V0(V0SEXP);
    Rcpp::traits::input_parameter< int >::type nrank(nrankSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type conv(convSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< double >::type inner_conv(inner_convSEXP);
    Rcpp::traits::input_parameter< int >::type inner_iter(inner_iterSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type WA(WASEXP);
    rcpp_result_gen = Rcpp::wrap(srrr_Rcpp(Y, X, method, A0, V0, nrank, lambda, conv, maxiter, inner_conv, inner_iter, WA));
    return rcpp_result_gen;
END_RCPP
}
// surr_fit_Rcpp
Rcpp::List surr_fit_Rcpp(arma::mat Y, arma::mat X, double lambda, arma::vec U0, arma::vec V0, arma::vec WU, arma::vec WV, arma::mat Xtran, Rcpp::List control);
RcppExport SEXP _rrpack_surr_fit_Rcpp(SEXP YSEXP, SEXP XSEXP, SEXP lambdaSEXP, SEXP U0SEXP, SEXP V0SEXP, SEXP WUSEXP, SEXP WVSEXP, SEXP XtranSEXP, SEXP controlSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type U0(U0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type V0(V0SEXP);
    Rcpp::traits::input_parameter< arma::vec >::type WU(WUSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type WV(WVSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Xtran(XtranSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type control(controlSEXP);
    rcpp_result_gen = Rcpp::wrap(surr_fit_Rcpp(Y, X, lambda, U0, V0, WU, WV, Xtran, control));
    return rcpp_result_gen;
END_RCPP
}
// kron_RcppArma
arma::mat kron_RcppArma(arma::mat A, arma::mat B);
RcppExport SEXP _rrpack_kron_RcppArma(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type A(ASEXP);
    Rcpp::traits::input_parameter< arma::mat >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(kron_RcppArma(A, B));
    return rcpp_result_gen;
END_RCPP
}
