##' Summarize rrpack Objects
##'
##' S3 methods summarizing objects generated by \code{rrpack}.
##'
##' @name summary
##'
##' @param object Object generated from \code{rrpack}.
##' @param ... Other argumnts for future usage.
NULL


##' @rdname summary
##' @export
summary.mrrr <- function(object, ...)
{
  class(object) <- "summary.mrrr"
  object
}


##' @rdname summary
##' @export
summary.cv.mrrr <- function(object, ...)
{
  class(object) <- "summary.cv.mrrr"
  object
}


##' @rdname summary
##' @export
summary.r4 <- function(object, ...)
{
  class(object) <- "summary.r4"
  object
}


##' @rdname summary
##' @export
summary.rrr <- function(object, ...)
{
  class(object) <- "summary.rrr"
  object
}


##' @rdname summary
##' @export
summary.cv.rrr <- function(object, ...)
{
  class(object) <- "summary.cv.rrr"
  object
}


##' @rdname summary
##' @export
summary.sofar <- function(object, ...)
{
  class(object) <- "summary.sofar"
  object
}


##' @rdname summary
##' @export
summary.cv.sofar <- function(object, ...)
{
  class(object) <- "summary.cv.sofar"
  object
}


##' @rdname summary
##' @export
summary.srrr <- function(object, ...)
{
  class(object) <- "summary.srrr"
  object
}


##' @rdname summary
##' @export
summary.cv.srrr <- function(object, ...)
{
  class(object) <- "summary.cv.srrr"
  object
}


##' @rdname summary
##' @export
summary.rssvd <- function(object, ...)
{
  class(object) <- "summary.rssvd"
  object
}
